import React from 'react';
import './App.css'; 
import FormComponent from './components/FormSteps/FormComponent'; 
import ResumePreview from './components/Preview/ResumePreview'; 
import TemplateSelector from './components/TemplateSelector'; 
import PdfDownloader from './components/PdfDownloader'; 
import ThemeToggle from './components/ThemeToggle'; 
// --- IMPORT TEMPLATE CSS FILES ---
import './components/Templates/Template1.css';
import './components/Templates/Template2.css';
import './components/Templates/Template3.css';


function App() {
  return (
<div>
  <div style={{ position: 'absolute', top: '15px', right: '20px', zIndex: 10 }}>
    <ThemeToggle /> 
  </div>
  <div className="App">
    <h1>AI Resume Builder</h1>
    <div className="form-section">
      <h2>Build Your Resume</h2>
      <TemplateSelector /> 
      <FormComponent /> 
    </div>
    <div className="preview-section">
      <h2>Live Preview</h2>
      <PdfDownloader />
      <div className="resume-preview-container" id="resume-preview-content">
        {/* The content inside here will be generated by ResumePreview */}
        <ResumePreview />
      </div>
    </div>
  </div>
</div>
  );
}

export default App;

// Note: If want multi-page routing later (e.g., landing page),
// you'd import BrowserRouter, Routes, Route from 'react-router-dom'
// and structure your routes here. For now, a single page layout is simpler.
