import React from 'react';
import './App.css'; // Import base App styles
import FormComponent from './components/FormSteps/FormComponent'; // We'll create this
import ResumePreview from './components/Preview/ResumePreview'; // We'll create this
import TemplateSelector from './components/TemplateSelector'; // We'll create this
import PdfDownloader from './components/PdfDownloader'; // We'll create this
import ThemeToggle from './components/ThemeToggle'; //theme toggle

// --- IMPORT TEMPLATE CSS FILES ---
import './components/Templates/Template1.css';
import './components/Templates/Template2.css';
import './components/Templates/Template3.css';
// Import other template CSS files here as you add them

function App() {
  return (
<div>
  <div style={{ position: 'absolute', top: '15px', right: '20px', zIndex: 10 }}>
    <ThemeToggle /> {/* <-- RENDER THE BUTTON */}
  </div>
  <div className="App">
    <h1>AI Resume Builder</h1>
    <div className="form-section">
      <h2>Build Your Resume</h2>
      <TemplateSelector /> {/* Add template selector */}
      <FormComponent /> {/* The main form */}
    </div>
    <div className="preview-section">
      <h2>Live Preview</h2>
      <PdfDownloader /> {/* Add download button */}
      <div className="resume-preview-container" id="resume-preview-content">
        {/* The content inside here will be generated by ResumePreview */}
        <ResumePreview />
      </div>
    </div>
  </div>
</div>
  );
}

export default App;

// Note: If you want multi-page routing later (e.g., landing page),
// you'd import BrowserRouter, Routes, Route from 'react-router-dom'
// and structure your routes here. For now, a single page layout is simpler.